### ISSUE TITLE
Did you code the ESPTimeHelper that is included inside ESP_Mail_Client?

### ISSUE THREAD

**Issue by Rcates1** [mobizt/ESP32-Time-Helper#1]
To me looks like this was the first attempt at this and looks abandoned. The version included looks a lot more refined.

Anyway, I cannot find any example files for this, and also it does not look like ESP_MAIL_Client pulls anything from this library but from time.h instead. I would like to get the day of the week to show up on my emails. can you make some examples of this? and update this code.  

Thanks in advance

**Comment by mobizt** [comment]
The ESPTimeHelper is the built-in class used in ESP Mail Client library for time settings from NTP servers and time string building and parsing e.g.
- Used in server authorization process when SSL certificate provided in ESP8266 and ESP32.
- Used when Date header was set in SMTP request or in [RFC822 envelope](https://github.com/mobizt/ESP-Mail-Client/blob/6f467f9be754e225a44a8283cdaf266ec17cbe48/examples/SMTP/Send_RFC822_Attachment/Send_RFC822_Attachment.ino#L165).
- Used when [Date header parsing](https://github.com/mobizt/ESP-Mail-Client/blob/6f467f9be754e225a44a8283cdaf266ec17cbe48/examples/IMAP/Search_Emails/Search_Emails.ino#L374) to timestamp in IMAP response.

You can use ESPTimeHelper as the member functions of the ESP Mail Client class as **MailClient.Time.<functions>**

I don't know what you mean "to get the day of the week to show up on my emails" as the Date from IMAP header is already provide this day of the week e.g. **"Fri 24 Dec 2021 08:00:00 +0000"**.

This is the [functions descriptions of ESPTimeHelper](https://github.com/mobizt/ESP-Mail-Client/tree/master/src#mailclienttime-functions).
